"""update post_history table for carousel post

Revision ID: c012b65c4d15
Revises: cb441000f663
Create Date: 2025-04-03 17:41:23.981265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c012b65c4d15'
down_revision: Union[str, None] = 'cb441000f663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_post_history', sa.Column('children', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_post_history', 'children')
    # ### end Alembic commands ###
